//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestautantEntities : DbContext
    {
        public RestautantEntities()
            : base("name=RestautantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergen> Alergens { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
    
        public virtual ObjectResult<OrderAscProdByPrice_Result> OrderAscProdByPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderAscProdByPrice_Result>("OrderAscProdByPrice");
        }
    
        public virtual ObjectResult<OrderAscProdBySpecificPrice_Result> OrderAscProdBySpecificPrice(Nullable<decimal> lwrLimit, Nullable<decimal> upperLimit)
        {
            var lwrLimitParameter = lwrLimit.HasValue ?
                new ObjectParameter("lwrLimit", lwrLimit) :
                new ObjectParameter("lwrLimit", typeof(decimal));
    
            var upperLimitParameter = upperLimit.HasValue ?
                new ObjectParameter("upperLimit", upperLimit) :
                new ObjectParameter("upperLimit", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderAscProdBySpecificPrice_Result>("OrderAscProdBySpecificPrice", lwrLimitParameter, upperLimitParameter);
        }
    
        public virtual ObjectResult<OrderDescProdByPrice_Result> OrderDescProdByPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderDescProdByPrice_Result>("OrderDescProdByPrice");
        }
    
        public virtual ObjectResult<OrderDescProdBySpecificPrice_Result> OrderDescProdBySpecificPrice(Nullable<decimal> lwrLimit, Nullable<decimal> upperLimit)
        {
            var lwrLimitParameter = lwrLimit.HasValue ?
                new ObjectParameter("lwrLimit", lwrLimit) :
                new ObjectParameter("lwrLimit", typeof(decimal));
    
            var upperLimitParameter = upperLimit.HasValue ?
                new ObjectParameter("upperLimit", upperLimit) :
                new ObjectParameter("upperLimit", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderDescProdBySpecificPrice_Result>("OrderDescProdBySpecificPrice", lwrLimitParameter, upperLimitParameter);
        }
    
        public virtual ObjectResult<SelectMenuByProdName_Result> SelectMenuByProdName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMenuByProdName_Result>("SelectMenuByProdName", nameParameter);
        }
    
        public virtual ObjectResult<SelectProductsByCateg_Result> SelectProductsByCateg(string categ)
        {
            var categParameter = categ != null ?
                new ObjectParameter("categ", categ) :
                new ObjectParameter("categ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectProductsByCateg_Result>("SelectProductsByCateg", categParameter);
        }
    
        public virtual ObjectResult<SelectProductsByName_Result> SelectProductsByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectProductsByName_Result>("SelectProductsByName", nameParameter);
        }
    }
}
